language: node_js
node_js: "12"
branches:
  	only:
    	- master
cache:
  	directories:
   		- node_modules
deploy:
  	provider: heroku
  	api_key:
    	secure: "cbd1a56f-99bc-4a82-a631-ab85ed1fd504"
  	app: donateright